"""city, unique full name, nullable weather and air quality

Revision ID: 2250d093f4e6
Revises: a047005a0285
Create Date: 2025-09-09 08:57:49.862606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column, delete

# revision identifiers, used by Alembic.
revision = '2250d093f4e6'
down_revision = 'a047005a0285'
branch_labels = None
depends_on = None


def upgrade():
    employee_assignments_table = table('employee_assignments', column('id'))
    air_quality_table = table('air_quality', column('id'))
    weather_table = table('weather', column('id'))
    work_locations_table = table('work_locations', column('id'))
    
    op.execute(delete(employee_assignments_table))
    op.execute(delete(air_quality_table))
    op.execute(delete(weather_table))
    op.execute(delete(work_locations_table))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('air_quality', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['full_name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('work_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('city')

    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('air_quality', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
