"""database revision

Revision ID: 4a23a67909b9
Revises: 2250d093f4e6
Create Date: 2025-09-11 10:09:48.993033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a23a67909b9'
down_revision = '2250d093f4e6'
branch_labels = None
depends_on = None


def upgrade():
    # Hapus data dengan urutan yang benar agar tidak melanggar foreign key
    op.execute('DELETE FROM employee_assignments')
    op.execute('DELETE FROM health_records')
    op.execute('DELETE FROM air_quality')
    op.execute('DELETE FROM weather')
    op.execute('DELETE FROM employees')
    op.execute('DELETE FROM diseases')
    op.execute('DELETE FROM work_locations')
    op.execute('DELETE FROM hazards')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('air_quality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('air_quality_index', sa.Integer(), nullable=True))
        batch_op.drop_column('co_level')
        batch_op.drop_column('aqi')
        batch_op.drop_column('pm25')
        batch_op.drop_column('pm10')

    with op.batch_alter_table('employee_assignments', schema=None) as batch_op:
        batch_op.alter_column('work_location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('uq_employee_assignment', ['employee_id', 'work_location_id', 'department', 'division', 'position', 'level'])

    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.drop_column('exposure_limit')

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration_stay', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_cases', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('high_risk', sa.Integer(), nullable=True))
        batch_op.drop_column('record_date')
        batch_op.drop_column('excess_not_paid')
        batch_op.drop_column('coverage_id')
        batch_op.drop_column('record_type')
        batch_op.drop_column('excess_paid')
        batch_op.drop_column('claim_status')

    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weather_condition', sa.String(length=100), nullable=True))
        batch_op.drop_column('humidity')
        batch_op.drop_column('temperature')
        batch_op.drop_column('wind_speed')

    with op.batch_alter_table('work_locations', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               type_=sa.Numeric(precision=18, scale=15),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               type_=sa.Numeric(precision=18, scale=15),
               existing_nullable=True)
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.alter_column('longitude',
               existing_type=sa.Numeric(precision=18, scale=15),
               type_=sa.NUMERIC(precision=9, scale=6),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Numeric(precision=18, scale=15),
               type_=sa.NUMERIC(precision=9, scale=6),
               existing_nullable=True)

    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('weather_condition')
        batch_op.drop_column('average_temperature')
        batch_op.drop_column('max_temperature')
        batch_op.drop_column('min_temperature')

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('excess_paid', sa.NUMERIC(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('record_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('coverage_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('excess_not_paid', sa.NUMERIC(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('record_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('high_risk')
        batch_op.drop_column('daily_cases')
        batch_op.drop_column('duration_stay')
        batch_op.drop_column('status')
        batch_op.drop_column('admission_date')

    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exposure_limit', sa.NUMERIC(), autoincrement=False, nullable=True))

    with op.batch_alter_table('employee_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_assignment', type_='unique')
        batch_op.alter_column('work_location_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('air_quality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pm10', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pm25', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('aqi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('co_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('air_quality_index')

    # ### end Alembic commands ###
